# Generated by Django 4.1 on 2022-08-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_detail', models.TextField()),
                ('movie_image', models.ImageField(upload_to='movie-list/images/')),
            ],
        ),
    ]
